---
- name: Add webupd8 java repository.
  apt_repository:
    repo: 'ppa:webupd8team/java'
  register: webupd8_repo

- name: Add key for webupd8 repository.
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: EEA14886

- name: Accept Oracle java license
  debconf:
    name: oracle-java{{ oracle_java_version }}-installer
    question: shared/accepted-oracle-license-v1-1
    value: 'true'
    vtype: select

- name: Install Oracle java package
  apt:
    name: 'oracle-java{{ oracle_java_version }}-installer'
    state: '{{ oracle_java_state }}'

- name: Set java environment variables
  apt:
    name: 'oracle-java{{ oracle_java_version }}-set-default'
    state: '{{ oracle_java_state }}'
  when: oracle_java_set_default
